# Generated by Django 2.2.7 on 2019-11-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='令牌')),
                ('deadline', models.DateTimeField(verbose_name='有效时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iot.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备令牌',
                'verbose_name_plural': '设备令牌',
            },
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
