# Generated by Django 2.2.7 on 2019-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20191124_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'verbose_name': '设备口令', 'verbose_name_plural': '设备口令'},
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.TextField(verbose_name='测量时间'),
        ),
    ]
