# Generated by Django 2.2.7 on 2019-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20191124_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.TextField(blank=True, null=True, verbose_name='测量时间'),
        ),
    ]
