# Generated by Django 2.2.7 on 2019-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20191124_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设备编码'),
        ),
        migrations.AddField(
            model_name='device',
            name='gps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设备坐标'),
        ),
        migrations.AddField(
            model_name='device',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设备秘钥'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='传感器编码'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='临时口令'),
        ),
    ]
