"""
Django settings for IotRestfulHome project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7ag2+4iv_it_#(zd*@x5yn50p3q69xtzux5m861u)#^8*eq5*@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['iot.lubangongju.com','127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'iot.apps.IotConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IotRestfulHome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'IotRestfulHome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# AUTH_USER_MODEL = 'iot.UserProfile'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

import time
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['数据管理', '设备管理', '用户管理', '数据分析'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
         {
             'name': '数据管理',
              'icon': 'fas fa-code',
             'models': [{
                 'name': '数据点',
                  'icon': 'fa fa-user',
                  'url': 'iot/datapoint/' }
                 ,{
                 'name': '上传帮助',
                  'icon': 'fa fa-user',
                  'url': 'addhelp/' }]}
        ,{
             'name': '设备管理',
             'icon': 'fa fa-file',
              'models': [ {
                 'name': '设备',
                  'url': 'iot/device/',
                 'icon': 'far fa-surprise'}
            ,{
                 'name': '设备口令',
                 'url': 'iot/devicetoken/',
                 'icon': 'fab fa-github'
             }
                ,{
                  'name': '传感器类型',
                 'url': 'iot/sensortype/',
                 'icon': 'fab fa-github'
             }
            , {
                 'name': '传感器',
                 'url': 'iot/sensor/',
                 'icon': 'fab fa-github'
              }
        ]
    }
        ,{
            'app': 'auth',
            'name': '用户管理',
            'icon': 'fas fa-user-shield',
             'models': [{
                 'name': '用户',
                 'icon': 'fa fa-user',
                 'url': 'auth/user/'}
             ,{
                'name': '用户组',
                'url': 'auth/group/',
                 'icon': 'far fa-surprise'}]
        }
        ,{
        'name': '数据分析' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '湿度',
            'url': 'humidity',
            'icon': 'far fa-surprise'
        },{
            'name': '温度',
            'url': 'temperature',
            'icon': 'far fa-surprise'
        },{
            'name': '设备',
            'url': 'datalist',
            'icon': 'far fa-surprise'
        }]
    }
    ]
}

SIMPLEUI_HOME_INFO = False
